---
title: "Team Contribution"
author: "Nathan Collinsworth, Bryce Butler, Thomas Robbins, Eric Fingar"
date: "2023-12-5"
output: html_notebook
---

This is the team contribution notebook.

Nathan Collinsworth: 


Bryce Butler: 
Added Labels and Metro Station Points to Ridership and Distance to Metro graph
Removed NA from station_id column in df_bike_stations_nearest_metro
Added a regression model that calculated the percentage increase in ridership per mile decrease in distance to metro station


Thomas Robbins: 
Created original plots and data exploration surrounding ridership, weather data, and metro access.
Added Rmd file for spatial analysis of demographic/census data, allowing for potential future cross-referencing of our results with demographic and socioeconomic factors.
Creating structure of final submission repository and organizing files, including initial creation of metro_bikeshare_final Rmd.
Iteratively updated final project analysis, including multiple steps of refinement of visualizations, as well as assembly of initial scatter plot.
Finalized all visualizations and refined annotations throughout the final Rmd for reporting submission.

Eric Fingar: 
Initially read in data from riderhip file and metro station entrances file and cleaned it for use in data frames.
Additionaly cleaning and merging of the dataframes df1, df2, dfinto one for use in data analysis (df_cleaned)
Created a basic model that plotted the bikeshare ridership vs how far the station was from the closest metro station entrance
