---
title: "metro_bikeshare_final"
author: "Bryce Butler"
date: "2023-12-5"
output: html_document
---


```{r}
library(tidyverse)
library(janitor)
library(here)
library(rwunderground)
library(openmeteo)
library(ggplot2)
library(geosphere)
library(plotly)
library(rstanarm)
#library(read)
```


```{r}
thisfile=here("data_raw", "202305-capitalbikeshare-tripdata.zip")

df1=read_csv(thisfile) %>% clean_names()
```

```{r}
thisfile=here("data_raw","Metro_Station_Entrances_in_DC.csv")

dfM=read_csv(thisfile) |> clean_names()
```


```{r}
# Combine start and end data
df2s <- df1 %>%
  select(rideable_type, member_casual, contains("start"), ride_id) %>% 
  mutate(start_stop = "start") %>%
  rename(t = started_at, station_name = start_station_name, station_id = start_station_id, lat = start_lat, lng = start_lng)

df2e <- df1 %>%
  select(ride_id, rideable_type, member_casual, contains("end")) %>%
  mutate(start_stop = "stop") %>%
  rename(t = ended_at, station_name = end_station_name, station_id = end_station_id, lat = end_lat, lng = end_lng)

df2 <- bind_rows(df2s, df2e) %>%
  arrange(t) %>%
  mutate(rider_delta = (start_stop == "start") * 2 - 1) %>% # change in ridership 
  mutate(riders = cumsum(rider_delta)) %>%
  relocate(riders, .after = t)

```

```{r}
# Create a dataframe with total ridership, lat, lng for unique station IDs
df_total_ridership <- df2 %>%
  group_by(station_id, lat, lng) %>%
  summarise(total_ridership = max(riders)) %>%
  ungroup()

```

```{r}

# Create a new dataframe with only lat and long columns
df_metro_coordinates <- data.frame(lat = dfM$y, lng = dfM$x)

```

```{r}

# Create df_cleaned with total_ridership, latbike, and lngbike
df_total_ridership_sum <- df_total_ridership %>%
  group_by(station_id) %>%
  summarise(
    total_ridership = sum(total_ridership),
    latbike = first(lat),  # Assuming lat and lng are the original columns
    lngbike = first(lng)   # Adjust if your columns are named differently
  )

# Add metro station coordinates with swapped column names
df_cleaned <- merge(
  df_total_ridership_sum,
  df_metro_coordinates %>% select(lat, lng) %>% rename(latmetro = lat, lngmetro = lng),
  by = character(),
  all.x = TRUE
)

```

```{r}
# Assuming df_cleaned has the columns "latbike", "lngbike", "latmetro", "lngmetro"
df_cleaned_with_distance <- df_cleaned %>%
  rowwise() %>%
  mutate(
    dist_to_metro = distHaversine(c(lngbike, latbike), c(lngmetro, latmetro)) / 1609.344
  )

```

```{r}
#sumarise cleaned_with_distance with the minimum distance to a metro station for each bike station
df_nearest_metro = df_cleaned_with_distance |>
  select(station_id, total_ridership, latbike, lngbike, dist_to_metro) |>
  group_by(station_id) |>
  summarise(min_dist_to_metro = min(dist_to_metro))

#create dataframe that has only one entry for each bike station with the distance to the nearest metro station
df_bike_stations_nearest_metro = df_total_ridership_sum |>
  left_join(df_nearest_metro, by = join_by(station_id == station_id))

#remove NA
df_bike_stations_nearest_metro <- na.omit(df_bike_stations_nearest_metro)
```


Plotting ridership vs distance to metro:
```{r}

ggplot(df_bike_stations_nearest_metro, aes(x = min_dist_to_metro, y = total_ridership))+
    geom_point(alpha = 0.5, color = "#074650", size = 0.75) +
    geom_smooth(method = "loess", se = FALSE,
                color = "limegreen", linewidth = 1.5) +  
  labs(title = "Relationship between Ridership and Distance to Metro",
       x = "Distance to Metro (miles)",
       y = "Total Ridership" ) +
  xlim(0,25) +
  ylim(0,150000)
  #theme_minimal()

```

```{r}
#add enum distance category for stations
df_bike_stations_nearest_metro = df_bike_stations_nearest_metro |> 
  mutate(distance_category = case_when(
    min_dist_to_metro <= 0.1 ~ "<= 0.1 miles",
    min_dist_to_metro <= 0.5 ~ "<= 0.5 miles",
    min_dist_to_metro <= 1   ~ "<= 1 miles",
    min_dist_to_metro <= 5   ~ "<= 5 miles",
    TRUE                     ~ "> 5 miles",
  ))

```


plotting ridership and metro locations
```{r}
p1 = df_bike_stations_nearest_metro |>
  ggplot(aes(x = lngbike, y = latbike, color = min_dist_to_metro, size = total_ridership)) +
  scale_color_gradientn(colors = c("darkgreen", "yellow", "red"), trans = "log10") +
  geom_point(alpha = 0.25) +
  geom_point(data = df_metro_coordinates, aes(x = lng, y = lat), color = "blue", size = .1) + #metro station locations
  labs(title = "Ridership and Distance to Metro", x = "Latitude", y = "Longitude")

plotly::ggplotly(p1)
```

regression model for ridership
```{r}
# regression model that uses a linear model on the log of total ridership 
bike_model <- lm(log(total_ridership) ~ min_dist_to_metro, data = df_bike_stations_nearest_metro)
```

```{r}
coef <- coef(bike_model)
delta_distance <- -1  # Decrease distance to metro station by 1 mile
percentage_increase <- 100 * (exp(coef["min_dist_to_metro"])^delta_distance - 1)
cat("Percentage Increase in Ridership per Mile Decrease in Distance to Metro:", percentage_increase, "%")
```
