---
title: "september 2023 bikeshare"
author: "Nathan Collinsworth, Bryce Butler, Thomas Robbins"
output: html_notebook
---


```{r}
library(tidyverse)
library(janitor)
library(here)
library(rwunderground)
library(openmeteo)
library(plotly)
```


```{r}
thisfile=here("data_raw", "202309-capitalbikeshare-tripdata.zip")

df1=read_csv(thisfile) %>% clean_names()
```

```{r}
df2s=df1 %>% 
  select(rideable_type,member_casual,
                    contains("start"),ride_id) %>% 
  mutate(start_stop="start") %>%
  rename(t=started_at,
         station_name=start_station_name,
         station_id=start_station_id,
         lat=start_lat,
         lng=start_lng)
df2e=df1 %>% 
  select(ride_id,rideable_type,member_casual,
                    contains("end")) %>%
  mutate(start_stop="stop") %>%
  rename(t=ended_at,
         station_name=end_station_name,
         station_id=end_station_id,
         lat=end_lat,
         lng=end_lng)
 
df2=bind_rows(df2s,df2e) %>%
  arrange(t) %>%
  mutate(rider_delta=(start_stop=="start")*2-1) %>% #change in ridership 
  mutate(riders=cumsum(rider_delta)) %>%
  relocate(riders,.after=t)
```

```{r}
df2 %>% 
  ggplot(aes(t,riders)) +
  geom_line()
```

```{r}
df_r=df2 |>
  mutate(t_f=floor_date(t,"10 mins")) %>%
  relocate(t_f,.after=t) %>%
  slice_head(n=1,by=t_f)
```


```{r}
p1=df2 %>% 
  filter(day(t)==18) %>%
  ggplot(aes(t,riders)) +
  geom_line() +
  ggtitle("Riders on 18Sep")
p1+
  geom_line(data=df_r %>% filter(day(t)==18),
  color="red")
```

```{r}
df_w=weather_history("Washington",
                    start = "2023-09-01",
                    end = "2023-09-30",
                    hourly = c("apparent_temperature",
                               "wind_speed_10m",
                               "precipitation")
)
```

```{r}

df2c=df2 %>% mutate(t=force_tz(t,tzone="America/New_York")) #corrected
 
#df_s2=df2c %>% slice_sample(n=1000)
 
dfc=df2c %>% 
  left_join(df_w,by=join_by(closest(t>=datetime)))  %>%
  relocate(datetime, .after=t) |>
  rename(atemp=hourly_apparent_temperature,
         wind=hourly_wind_speed_10m,
         precipitation=hourly_precipitation)

head(dfc)
```

```{r}
df_r=dfc |>
  mutate(t_f=floor_date(t,"10 mins")) %>%
  relocate(t_f,.after=t) %>%
  slice_head(n=1,by=t_f)


p2=df_r |>
  ggplot(aes(t,riders, color=precipitation>1)) +
  geom_point()

p2
plotly::ggplotly(p2)
```


```{r}
p3=dfc |>
  filter(day(t) == 23) |>
  ggplot(aes(t,riders, color=precipitation>1, shape=rideable_type)) +
  geom_point()

p3
plotly::ggplotly(p3)
```

```{r}
df1d = df1 |>
  mutate(ride_time = ended_at - started_at) |>
  filter(ride_time > 30) |>
  filter(ride_time < 7200) # 2 hours
  #filter(ride_time < 10800) # 3 hours
  #filter(ride_time < 86400) # one day

df1d |>
  ggplot(aes(ride_time)) +
  geom_histogram()
```

